#!/bin/sh
if [ -z "$SUBSYSTEM" ]; then
    echo "SUBSYSTEM not defined, exiting"
    exit -1
fi

MAX_LOOPS=1024
UDEV_RULES_FILE=/etc/udev/rules.d/60-persistent-${SUBSYSTEM}.rules
if [ $SUBSYSTEM = "net" ]; then
    TARGET="NAME"
    ADD=""
else
    TARGET="SYMLINK"
    ADD="+"
fi
