#!/bin/sh

. /etc/udev/functions.udev

NET_ADDRESS=$1
[ -z "`echo $NET_ADDRESS | tr -d '0:'`" ] && exit 0

read_rules

INTERFACE_BASE=`echo $INTERFACE | sed -e 's/[0-9]*$//'`
INTERFACE_IFTAB=`awk "{ if (\\$3 == \"$NET_ADDRESS\") { print \\$1; exit } }" /etc/iftab`
if [ -n "$INTERFACE_IFTAB" ] && ! already_exists "$INTERFACE_IFTAB"; then
    RESULTS=$INTERFACE_IFTAB
else
    add_first_available $INTERFACE_BASE
fi

write_rule "SYSFS{address}==\"$NET_ADDRESS\""
echo $RESULTS
